- URI 1003.py
> Melhor formatação de visualização para v. Py 2.7

- URI 1005.c
- Identação corrigida e separação de operações
> Formatação de código e visualização

- URI 1933.c
> Identação e formatação de código

- URI 2602.SQL
Melhor visualização da query e identificação
> Separação palavras reservadas para a query em SQL.

- Uri - 1181
matriz = []
somatorio = 0
linha = int(input())
operacao = str(input())
for i in range(12):
matriz.append( [0] * 12 )
for i in range(12):
for j in range(12):
matriz[i][j] = float(input())
for i in range(12):
somatorio += matriz[linha][i]
media = somatorio/12
if operacao == "S":
print("{:.1f}".format(somatorio))
else:
print("{:.1f}".format(media))
> Uri - 1181.py

- uri-1021.py
Resolução referente a questão do uri de número 1021
> URI 1021.py

- uri-2378.c
Resolução referente a questão do uri de número 2378
> URI 2378.c

- resolucaoURI1367
Resolução de uma questão do URI. Questão número 1367
> URI 1367.c

- uri-1550.c
Resolução referente a questão do uri de número 1550
> URI 1550.c

- resolucaoURI1610.cpp
Resolução da questão 1610 do URI.
> URI 1610.cpp

- uri-1789.py
Resolução referente a questão do uri 1789
> URI 1789.py

- resolucaoURI1472.c
Resolução de uma questão do URI, questão número 1472
> URI 1472.c

- Uri - 2968
Resolução problema do uri 2968
> URI 2968.py

- Uri - 1533
> Create Uri - 1533

- Uri - 1042
entrada = list(map(int, input().split()))
entrada1 = sorted(entrada)
for i in entrada1:
print(i)
print("")
for j in entrada:
print(j)
> Create Uri - 1042

- Uri - 1178
n = float(input())
vetor = [n]
print("N[0] = {:.4f}".format(n))
num = n
for i in range(1, 100):	
valor = num/2
num = valor
vetor.append(valor)
print("N[{}] = {:.4f}".format(i, vetor[i]))
> Create Uri - 1178

- URI 2904.c
Resolução da do problema 2904 - Building a Field.
> URI 2904.c

- URI 1000.js
- URI 1001.js
- URI 1002.js
- URI 1003.js
- URI 1004.js
- URI 1005.js
- URI 1006.js
- URI 1007.js
- URI 1008.js
- URI 1009.js
- URI 1010.js
Eae @ivanjosiel ! Aqui vai algumas soluções com JavaScript dos problemas 1000 até 1005! o/
> Soluções com JavaScript

- URI 1279.py
- URI 1318.py
> URI 1279 e 1318

- JavaScript/URI 1011.js
> Create URI 1011.js

- JavaScript/URI 1012.js
feat: new file soluction question 1012 js
> Create URI 1012.js
